### ISSUE TITLE
URL to close the quizz

### ISSUE THREAD

**Issue by juliends** [juliends/snow_party#82]
We need to provide an interface to close the quiz

**Comment by grmnlrt** [comment]
On a déjà le bouton sur `/quizzes/:quiz_id/close_quiz` 👇 

<img width="1440" alt="Capture d’écran 2019-05-31 à 17 07 34" src="https://user-images.githubusercontent.com/25386941/58715179-9d758a00-83c6-11e9-9eee-e52ada6fb1df.png">

Il faut juste refaire l'interface ? Est-ce qu'on en profite pour simplifier l'url pour Anne? (genre juste `/close`, et on retrouve le quiz avec `Quiz.last` dans l'action de controller).

**Comment by juliends** [comment]
Yes parfait 👍 
Il faut s'assurer que le bouton soit bien centré sur mobile et ajouter un `data-confirm` pour éviter les fausses manips

**Comment by juliends** [comment]
Pour retrouver le quiz cherche le `playable: true` pas le `last`

**Comment by db0sch** [comment]
pour l'avoir un bon bouton en mobile, je te conseille de faire un btn block
https://getbootstrap.com/docs/4.3/components/buttons/#sizes

Ca prend tout la largeur
